version: 2
updates:
  # Monitor JavaScript dependencies via npm
  - package-ecosystem: "npm"
    directory: "./vscode-extension"  # Adjust this if `package.json` is not in the root
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
        versions: ["8.57.0"]
            
   # Monitor Python dependencies via Poetry (using the pip ecosystem)
  - package-ecosystem: "pip"
    directory: "./python-package"  # Adjust this if `pyproject.toml` is not in the root
    schedule:
      interval: "weekly"